FILENAME REFFILE '/home/u64298341/sorteio_copa/Input_Potes.xlsx';
libname ttt "/home/u64298341/sorteio_copa";

options nonotes nosource;

proc datasets nowarn nolist nodetails lib=work kill;
run;
  
PROC IMPORT DATAFILE=REFFILE DBMS=XLSX OUT=WORK.IMPORT replace; GETNAMES=YES; RUN;
PROC SQL NOPRINT nowarnrecurs; SELECT DISTINCT MAX(POTE) INTO :QTDE_POTES FROM IMPORT; QUIT;
PROC SQL NOPRINT nowarnrecurs; SELECT DISTINCT COUNT(TIME) INTO :QTDE_TIMES_POR_POTE FROM IMPORT GROUP BY POTE; QUIT;

%PUT QTDE_POTES: &QTDE_POTES.;
%PUT QTDE_TIMES_POR_POTE: &QTDE_TIMES_POR_POTE.;

%MACRO EXTRAI;
%LET I = 1;
%LET J = 0;

%DO %WHILE (&I. <= &QTDE_POTES.);

	DATA POTE&I.;
		ID = 1;
		length _pais $200;
		SET WORK.IMPORT (WHERE=(POTE = &I.));
		RENAME Time=Time&I. Pais=Pais&I.;
		rnd&I. = rand('uniform');
		IF STRIP(Pais) = STRIP('CONCACAF') and STRIP(POTE) = 1 THEN SUM_TOTAL = rnd&I./1000;
		ELSE SUM_TOTAL = rnd&I.*20;
		CONSOLIDADA_PAIS = Pais;
		
_pais = cats('/', strip(Pais), '/');
COUNT_UEFA     = (index(_pais,'/UEFA/')     > 0);
COUNT_CONMEBOL = (index(_pais,'/CONMEBOL/') > 0);
COUNT_CONCACAF = (index(_pais,'/CONCACAF/') > 0);
COUNT_AFC      = (index(_pais,'/AFC/')      > 0);
COUNT_CAF      = (index(_pais,'/CAF/')      > 0);
drop pote ;
	RUN;
	
	%IF &J. >= 1 %THEN %DO;
		proc sql noprint nowarnrecurs;
			CREATE TABLE POSSIBILIDADES1 AS SELECT 

	CATX('|', A.CONSOLIDADA_PAIS, B.PAIS&I.) AS CONSOLIDADA_PAIS,
A.COUNT_UEFA     + B.COUNT_UEFA     AS COUNT_UEFA,
A.COUNT_CONMEBOL + B.COUNT_CONMEBOL AS COUNT_CONMEBOL,
A.COUNT_CONCACAF + B.COUNT_CONCACAF AS COUNT_CONCACAF,
A.COUNT_AFC      + B.COUNT_AFC      AS COUNT_AFC,
A.COUNT_CAF      + B.COUNT_CAF      AS COUNT_CAF,
    		 
			SUM(A.SUM_TOTAL,RND&I.) AS SUM_TOTAL,
			A.*,B.*
			
			FROM POSSIBILIDADES1 AS A
			FULL JOIN POTE&I. AS B ON (A.ID = B.ID)
having CALCULATED COUNT_UEFA <= 2 AND CALCULATED COUNT_CONMEBOL <= 1 AND CALCULATED COUNT_CONCACAF <= 1 AND CALCULATED COUNT_AFC <= 1 AND CALCULATED COUNT_CAF <= 1
			ORDER BY SUM_TOTAL;
		QUIT;

	%END;
	%ELSE %DO;
		DATA POSSIBILIDADES1; SET POTE&I.; RUN;
	%END;
	%let I = %sysevalf(&I.+1);
	%let J = %sysevalf(&J.+1);
%end;
%mend;
%EXTRAI;

DATA POSSIBILIDADES1; SET POSSIBILIDADES1 (DROP= CONSOLIDADA_PAIS _pais COUNT_CONMEBOL COUNT_CONCACAF COUNT_AFC COUNT_CAF RND:);/*8.179*/
IF COUNT_UEFA >= 1 AND COUNT_UEFA <= 2;
RUN;

%LET I_ATUAL = 1;
%LET I_ANTERIOR = 1;

PROC SQL NOPRINT nowarnrecurs;SELECT NOBS INTO :NOBS FROM SASHELP.VTABLE WHERE LIBNAME = "WORK" AND MEMNAME = "POSSIBILIDADES1"; QUIT;

%LET TENTATIVA_FRUSTADA = 0;

/* options notes; */
%MACRO LOOP;
%LET DUPLO_UEFA = 0;
	%DO %WHILE (&I_ATUAL. <= &QTDE_TIMES_POR_POTE.);
	
		PROC SQL NOPRINT nowarnrecurs;SELECT NOBS INTO :NOBS FROM SASHELP.VTABLE WHERE LIBNAME = "WORK" AND MEMNAME = "POSSIBILIDADES&I_ATUAL."; QUIT;
		%PUT ESCOLHA &I_ATUAL. - &NOBS. POSSIBILIDADES;
	
		%IF &NOBS. > 0 /*AND &DUPLO_UEFA. <= 4*/ %THEN %DO;
		
			DATA _GRUPO&I_ATUAL.; SET POSSIBILIDADES&I_ATUAL.;
			GRUPO = &I_ATUAL.;
			IF _N_ = 1;
			RUN;
			
			DATA ttt.GRUPO_FINAL;
			LENGTH GRUPO 8. TIME1_ TIME2_ TIME3_ TIME4_ $ 64;

				SET _GRUPO:;
				TIME1_ = STRIP(TIME1)||" ("||STRIP(PAIS1)||")";
				drop TIME1;
				RENAME TIME1_ = TIME1;
				TIME2_ = STRIP(TIME2)||" ("||STRIP(PAIS2)||")";
				drop TIME2;
				RENAME TIME2_ = TIME2;
				TIME3_ = STRIP(TIME3)||" ("||STRIP(PAIS3)||")";
				drop TIME3;
				RENAME TIME3_ = TIME3;
				TIME4_ = STRIP(TIME4)||" ("||STRIP(PAIS4)||")";
				RENAME TIME4_ = TIME4;
				drop TIME4;
				DROP ID PAIS: SUM_TOTAL;
			RUN;
			proc sort data=ttt.GRUPO_FINAL; by grupo; quit;
			
			PROC SQL noprint; SELECT DISTINCT SUM(CASE WHEN COUNT_UEFA > 1 THEN 1 ELSE 0 END) INTO :DUPLO_UEFA FROM ttt.GRUPO_FINAL; QUIT;
/* 			%if &DUPLO_UEFA. > 4 %then %do; */
/* 			%PUT DUPLO_UEFA: &DUPLO_UEFA.; */
/* 			%end; */

			%LET I = 1;			
			%DO %WHILE (&I. <= &QTDE_POTES.);
				PROC SQL NOPRINT nowarnrecurs; SELECT TIME&I. INTO :TIME&I. FROM _GRUPO&I_ATUAL.; QUIT;
/* 				%PUT TIME&I.: "&&TIME&I.."; */
				%LET I = %SYSEVALF(&I.+1);
			%END;
		
			%LET I_ATUAL = %SYSEVALF(&I_ATUAL.+1);
			
			DATA POSSIBILIDADES&I_ATUAL.; SET POSSIBILIDADES&I_ANTERIOR.;
				IF TIME1 = "&TIME1." THEN DELETE;
			RUN;
					
			%LET J = 2;			
			%DO %WHILE (&J. <= &QTDE_POTES.) ;
				DATA POSSIBILIDADES&I_ATUAL.; SET POSSIBILIDADES&I_ATUAL.;
					IF TIME&J. = "&&TIME&J.." THEN DELETE;
				RUN;				
				%LET J = %SYSEVALF(&J.+1);
			%END;
			%LET I_ANTERIOR = %SYSEVALF(&I_ANTERIOR.+1);
			
			%IF  &DUPLO_UEFA. > 4 %THEN %DO;
				%LET TENTATIVA_FRUSTADA = %SYSEVALF(&TENTATIVA_FRUSTADA.+1);			
				data TTT.TENTATIVA_FRUSTADA;
				TENTATIVA_FRUSTADA = &TENTATIVA_FRUSTADA.;
				PREENCHEU_ATE_GRUPO = &I_ATUAL.;
				run;

				DATA ttt.GRUPO_FINAL; SET ttt.GRUPO_FINAL; IF GRUPO >= &I_ATUAL. THEN DELETE; RUN;

				%PUT Tentativa Frustada #&TENTATIVA_FRUSTADA. no &I_ATUAL.º grupo - &DUPLO_UEFA. grupos com mais de 2 UEFA;
				DATA POSSIBILIDADES&I_ATUAL.; SET POSSIBILIDADES&I_ATUAL.;
				STOP;
				RUN;
				%LET I_ATUAL = %SYSEVALF(&I_ATUAL.-1);
				%LET I_ANTERIOR = %SYSEVALF(&I_ANTERIOR.-1);
				DATA POSSIBILIDADES&I_ATUAL.; SET POSSIBILIDADES&I_ATUAL.; IF _N_ ~= 1 AND COUNT_UEFA ~= 2; RUN;

			%END;

		
		%END;
		%ELSE %DO;
			%LET TENTATIVA_FRUSTADA = %SYSEVALF(&TENTATIVA_FRUSTADA.+1);
			%PUT Tentativa Frustada #&TENTATIVA_FRUSTADA. no &I_ATUAL.º grupo;
			
			data TTT.TENTATIVA_FRUSTADA;
			TENTATIVA_FRUSTADA = &TENTATIVA_FRUSTADA.;
			PREENCHEU_ATE_GRUPO = &I_ATUAL.;
			run;

			DATA ttt.GRUPO_FINAL; SET ttt.GRUPO_FINAL; IF GRUPO >= &I_ATUAL. THEN DELETE; RUN;
			
			PROC SQL noprint; SELECT DISTINCT SUM(CASE WHEN COUNT_UEFA > 1 THEN 1 ELSE 0 END) INTO :DUPLO_UEFA FROM ttt.GRUPO_FINAL; QUIT;
			%if &DUPLO_UEFA. > 4 %then %do;
						%PUT ENTROU DUPLO_UEFA -  &DUPLO_UEFA.;
			%end;
			
			PROC SQL NOPRINT NOWARNRECURS;
			DROP TABLE work.POSSIBILIDADES&I_ATUAL.;
			quit;
	
			%LET I_ATUAL = %SYSEVALF(&I_ATUAL.-1);
			%LET I_ANTERIOR = %SYSEVALF(&I_ANTERIOR.-1);
			DATA POSSIBILIDADES&I_ATUAL.; SET POSSIBILIDADES&I_ATUAL.; IF _N_ ~= 1; RUN;
			
		%END;
		
	%END;
	%PUT GRUPOS GERADOS COM SUCESSO!;
	%PUT Total de tentativas: &TENTATIVA_FRUSTADA.;
%MEND;
%LOOP;

PROC SQL;
CREATE TABLE VALIDACAO AS SELECT *, SUM(CASE WHEN COUNT(TIME1) = 1 THEN 1 ELSE 0 END,
										CASE WHEN COUNT(TIME2) = 1 THEN 1 ELSE 0 END,
										CASE WHEN COUNT(TIME3) = 1 THEN 1 ELSE 0 END,
										CASE WHEN COUNT(TIME4) = 1 THEN 1 ELSE 0 END) AS POTES_REPETIDOS,
									SUM(CASE WHEN index(TIME1,'(UEFA)') < 1 AND index(TIME1,'(UEFA)') > 2 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME2,'(UEFA)') < 1 AND index(TIME2,'(UEFA)') > 2 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME3,'(UEFA)') < 1 AND index(TIME3,'(UEFA)') > 2 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME4,'(UEFA)') < 1 AND index(TIME4,'(UEFA)') > 2 THEN 1 ELSE 0 END) AS VERIF_UEFA,
									CASE WHEN SUM(CASE WHEN index(TIME1,'(CONMEBOL)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME2,'(CONMEBOL)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME3,'(CONMEBOL)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME4,'(CONMEBOL)') > 1 THEN 1 ELSE 0 END) > 1 THEN 1 ELSE 0 END AS VERIF_CONMEBOL,
									CASE WHEN SUM(CASE WHEN index(TIME1,'(CONCACAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME2,'(CONCACAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME3,'(CONCACAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME4,'(CONCACAF)') > 1 THEN 1 ELSE 0 END) > 1 THEN 1 ELSE 0 END AS VERIF_CONCACAF,
									CASE WHEN SUM(CASE WHEN index(TIME1,'(AFC)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME2,'(AFC)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME3,'(AFC)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME4,'(AFC)') > 1 THEN 1 ELSE 0 END) > 1 THEN 1 ELSE 0 END AS VERIF_AFC,
									CASE WHEN SUM(CASE WHEN index(TIME1,'(CAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME2,'(CAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME3,'(CAF)') > 1 THEN 1 ELSE 0 END,
										CASE WHEN index(TIME4,'(CAF)') > 1 THEN 1 ELSE 0 END) > 1 THEN 1 ELSE 0 END AS VERIF_CAF,
									CASE WHEN SUM(CASE WHEN COUNT_UEFA = 2 THEN 1 ELSE 0 END) = 4 THEN 0 ELSE 1 END AS VERIF_DUPLA_UEFA,
									CASE WHEN SUM(CALCULATED POTES_REPETIDOS, CALCULATED VERIF_UEFA, CALCULATED VERIF_CONMEBOL, CALCULATED VERIF_CONCACAF, CALCULATED VERIF_AFC, CALCULATED VERIF_CAF, CALCULATED VERIF_DUPLA_UEFA) = 0 THEN "OK" ELSE "ERRO" END AS VALIDACAO_FINAL
FROM  ttt.GRUPO_FINAL;
QUIT;